name: fat_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.2.1
  video_player: ^2.9.1
  firebase_analytics: ^11.2.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  firebase_database: ^11.1.2
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1
  firebase_storage: ^12.3.0
  image_picker: ^1.0.0
  mailer: ^6.2.0
  camera: ^0.11.0+2
  videosdk: ^1.1.8
  http: ^1.2.2
  flutter_facebook_auth: ^6.0.4
  geocoding: ^2.1.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  google_fonts: ^4.0.0
  chewie: ^1.3.4
  youtube_player_flutter: ^8.0.0
  mocktail: ^0.3.0
  fake_cloud_firestore: 3.1.0
  google_sign_in: ^6.2.2
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.1.3
  zego_uikit_prebuilt_live_streaming: ^3.13.5
  random_string: ^2.3.1
  youtube_player_iframe: ^4.0.4
  flutter_admin_scaffold: ^1.3.0
  zego_zim: ^2.17.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - images/factutor_logo.png
    - images/bank/amazon.png
    - images/icon.png
    - images/bank/google.png
    - images/bank/paypal.png
    - images/bank/visa.png
    - images/logo.png
    - images/students.png
    - images/tutor.png
    - images/login_illustration.png
    - images/maths/chapter1.mp4
    - images/img_google.png
    - images/img_login.png
    - images/avata.jpg